name: Pylint

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      working-directory: ./api
    

    steps:
    - uses: actions/checkout@v2
    
    - name: show api
      run: ls -R
      working-directory: ${{env.working-directory}}      
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
      
    - name: Install dependencies
      run: |        
        python -m pip install --upgrade pip
        pip install pylint
      working-directory: ${{env.working-directory}}      
      
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
      working-directory: ${{env.working-derectory}}      
